tap "homebrew/bundle"
tap "homebrew/cask-fonts"
tap "homebrew/cask"
tap "homebrew/core"

cask_args appdir: "/Applications"

brew "bat"
brew "cmake"
brew "diff-so-fancy"
brew "gitui"
brew "jq"
brew "kubectl"
brew "neovim"
brew "nodeenv"
brew "pyenv"
brew "tree"

cask "docker"
cask "font-cica"
cask "google-chrome"
cask "google-japanese-ime"
cask "intellij-idea"
cask "karabiner-elements"
cask "slack"
cask "warp"

