tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
# tap "osx-cross/arm"
# tap "osx-cross/avr"
# tap "qmk/qmk"
brew "pyenv"
brew "neovim"
brew "bat"
brew "carthage"
brew "cocoapods"
brew "git"
brew "diff-so-fancy"
# brew "libimobiledevice", args: ["HEAD"]
brew "nodebrew"
brew "ruby-build"
brew "rbenv"
brew "ruby"
brew "tree"
brew "xcodegen"
brew "pwgen"
#brew "zplug"
# dbrew "qmk/qmk/qmk"
cask "font-cica"
# cask "wine-stable"
# cask "xquartz"
cask "iterm2"
cask "google-chrome"
cask "google-japanese-ime"
cask "docker"
# sha256 checksumエラーでてた
#cask "hyperswitch"
